### PR TITLE
JsonAdapter parses Link header

### PR DESCRIPTION
**Pull request by iunanua**
PR related to issue #84

### CODE REVIEW

**Comment by anderruiz** [comment]
1) We decided to use the same data structure as we think that in the end both are Links and should therefore be placed in the same location. We believe that noone is going to use HAL and LinkHeaders at the same time, but even in that situation we could potentially create a single consolidated _links structure. Our goal was also to be able to use the library exactly in the same way as HAL. However, if you prefer to use a different variable for Link Headers we are fine with that, just give us a name :)

2) Ok we will remove them

3) Ok

Waiting for your answer :)

**Comment by basti1302** [comment]
Regarding 1. I still think that it is confusing to from a maintenance perspective because two rather unrelated things share a single location in the model. Let's name the new thing `t.step.doc._linkHeaders`? How does that sound to you?

**Comment by basti1302** [comment]
Also, the check if this property is already there becomes uneccessary when you switch to a different name, I think.

**Comment by iunanua** [comment]
I just pushed the changes you suggested. 
Greetings.

**Comment by basti1302** [comment]
Just to let you know, I'm currently working on making #37 happen. When this is done, I'll publish a new version, including this new feature.

Lots of thanks for your awesome work here!

**Comment by iunanua** [comment]
Thank you! xD

**Comment by basti1302** [comment]
This has landed in 6.0.0.

But it causes a problem, which I only found out about after I published the release, see https://github.com/basti1302/traverson/issues/86 :-(

**Comment by anderruiz** [comment]
Hi Bastian, we are taking a look to the code to see if we can remove that dependency :)

**Comment by basti1302** [comment]
That's very nice of you! I might also take a look, if it can be solved by browserify-shim, but not sure when I get around to investigate.

**Comment by basti1302** [comment]
Oh, and if you find anything or want to discuss, please let's do so over at #86 :)

**Pull request merged**
