### PR TITLE
Added support for XHR withCrendentials

### PR DESCRIPTION
**Pull request by ricardoecosta**
Pull request regarding issue #48

### CODE REVIEW

**Comment by basti1302** [comment]
This looks very good!!

I have two things that I would like to adress before merging this into master

1) Could you add docs for this to the section in `api.markdown` where it talks about `withRequestOptions(options)`? One sentence just mentioning that the option is available and is only effective in the browser should be enough.

2) I have merged your commits into a separate branch <https://github.com/basti1302/traverson/tree/xhr-with-credentials> and changed the test you added slightly, so that it is not only executed in PhantomJS but in all browsers. It is still skipped in NodeJS, of course. See [this commit}(https://github.com/basti1302/traverson/commit/0667fd94ea734dee747b6e3c10a84801a6294aa0). 

Now, when I execute this test in a browser, it complains about the combination of xhr.withCredentials = true and the CORS header used by the Traverson test server.

Chromium:
```
XMLHttpRequest cannot load http://127.0.0.1:2808/. A wildcard '*' cannot be used in the 'Access-Control-Allow-Origin' header when the credentials flag is true. Origin 'http://localhost:2808' is therefore not allowed access.
```

Firefox:
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://127.0.0.1:2808/. (Reason: CORS header 'Access-Control-Allow-Origin' does not match '*').
```

I'm not sure why this works in PhantomJS, maybe PhantomJS is less strict here than the other browsers. However, I really would like this test to succeed in all browsers. I'll try to investigate this a bit more in the next few days (when I find some time), maybe traverson-test-server can send different CORS headers to solve this problem.

**Comment by ricardoecosta** [comment]
The test update makes perfect sense, thanks. I've updated the documentation as you suggested and also submitted a pull request to __traverson-test-server__ to fix the issue you mentioned - more details here: https://github.com/basti1302/traverson-test-server/pull/1

**Comment by basti1302** [comment]
Superb work. Many thanks! <3

**Comment by ricardoecosta** [comment]
Pleasure!

**Pull request merged**
