### PR TITLE
fix(builder): Method follow mutates original array

### PR DESCRIPTION
**Pull request by dimik**
Method should not mutate input data. Application logic can rely on this param

### CODE REVIEW

**Comment by basti1302** [comment]
Looks good. Could you fix the failing build? I'll merge it immediately when the build passes.

https://travis-ci.org/basti1302/traverson/builds/106232189

```
   lib/builder.js
    129 |  )
            ^ Missing semicolon.
```

Just a missing semicolon :-)

You can run the build locally by running `grunt` in the project directory if you want to check before committing/pushing.

Thanks for the contribution! <3

**Comment by dimik** [comment]
Done

**Comment by basti1302** [comment]
It would have been great if you could have squashed the commits, but whatever. Sure, I'll publish a new version soon-ish.

**Comment by basti1302** [comment]
This has landed in version 3.1.3. Thanks for again for the patch.

**Pull request merged**
