### PR TITLE
let jsonReplacer stringify body when set in requestOptions (#68)

### LINKED ISSUE #68: let jsonReplacer stringify body when set in requestOptions
Hello,

#65 almost allowed me to set a replacer but... it's stringifyed already before given to request in `lib/http_requests.js`:

```
  if (t.body) {
    requestOptions.body = JSON.stringify(t.body);
  }
```

I will attach a PR to propose a fix

### PR DESCRIPTION
**Pull request by JulienYo**
Fix #68

### CODE REVIEW

**Comment by basti1302** [comment]
I can see that this is good enough for now, for your use case.

However, looking at your example:

```
api = traverson
    .from(url)
    .withRequestOptions({
      jsonReplacer: iweJson.replacer,
      jsonReviver: iweJson.reviver,
      json: true
    })
    .parseResponseBodiesWith((body) => body)
    ...
```

I see to things that bother me. You are using a jsonReviver but still have to work around Traverson parsing the body itself by calling `.parseResponseBodiesWith((body) => body)`. This should not be neccessary. I'd like to add one more `if` in the right place, so that Traverson leaves the response body untouched when the request options have a jsonReviver. What do you think?

Second (and less relevant to your use case) I now realize there is some imbalance between JSON serialization and deserialization. Traverson already has a method to do custom JSON deserialization (parseResponseBodyWith) but not for custom serialization. I think I should add one for this, too.

**Comment by basti1302** [comment]
Hey @JulienYo,

could you do me a big favor? Could you test with current master if you can drop the `.parseResponseBodiesWith((body) => body)`? I don't have a test case with jsonReplacer/jsonReviver at hand (actually, before your bug report, I didn't even know these exist in request :smile_cat: ).

Kind regards
  Bastian

**Comment by JulienYo** [comment]
Hello & thanks!

Yes we use replacer/reviver for our serialisation (e.g. to keep dates as `Date` without schema).
I'll test current master ASAP

**Comment by JulienYo** [comment]
Hello,

Works like a charm without  `.parseResponseBodiesWith((body) => body)`, thank you!

**Comment by basti1302** [comment]
This has landed in release 3.2.0

**Pull request merged**
